name: countapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0
  permission_handler: ^11.3.0
  notification_listener_service: ^1.0.0
  shared_preferences: ^2.2.2
  logger: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  
  # ✅ 添加 assets 声明（用于其他图片资源）
  assets:
    - assets/image/  # 声明图片文件夹

# ✅ 修正后的图标配置
flutter_launcher_icons:
  android: true  # ✅ 改为 true
  ios: true
  image_path: "assets/image/MikuCount_title.png"  
  
  web:
    generate: true
    image_path: "assets/image/MikuCount_title.png"  
  
  windows:
    generate: true
    image_path: "assets/image/MikuCount_title.png"  
    icon_size: 48
  
  macos:
    generate: true
    image_path: "assets/image/MikuCount_title.png"  